version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: flask-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: StrongPass123!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: flask-app
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
