apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: flask
type: Opaque
stringData:
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "StrongPass123!"
  DB_HOST: "flask-db.csp6soueyf3p.us-east-1.rds.amazonaws.com"