name: Build infra docker build and deploy via eks 
on: 
  push: 
    branches: 
      - main
jobs: 
   build-and-deploy: 
     name: create infra 
     runs-on: ubuntu-latest 

     steps:
       - name: checkout-code
         uses: actions/checkout@V3 
       - name: Install terraform 
         uses: hashicorp/setup-terraform@v2 
         with: 
           terraform-version: 1.5.6 
       - name: 
