name: Build infra docker build and deploy via eks 
on: 
  push: 
    branches: 
      - main
jobs: 
   build-and-deploy: 
     name: create infra 
     runs-on: ubuntu-latest 

     steps:
       - name: checkout-code
         uses: actions/checkout@v3 
       - name: Install terraform 
         uses: hashicorp/setup-terraform@v2 
         with: 
           terraform-version: 1.5.6 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-1
       - name: Initialize terraform 
         run: terraform init 
         working-directory: ./flask-project/terraform
